# SPDX-License-Identifier: MemHouse-Sustainable-Use-1.0

defmodule MemHouse.Documents do
  @moduledoc """
  The public face of the document subsystem: ingest, sync, portability, and the two Ash
  resources that back them.

  Documents enter as bytes, not knowledge. After content-addressed storage and immutable
  versioning, they are parsed, chunked, embedded, extracted, and governed like messages.

  ## What this domain owns

  - `MemHouse.Documents.ConnectorConfig` — durable authored configuration for one external
    source: its schedule, its sync cursor, its content-safe settings, and a reference to (never
    a copy of) its credential.
  - `MemHouse.Documents.DocumentChunk` — a rebuildable derived cache. Chunks and their vectors
    can always be regenerated by re-parsing the version blob.

  Document identity and version history live with raw observations as system-of-record rows.

  ## Rules this subsystem guarantees

  - Re-submitting identical bytes is a no-op: the payload hash is compared against the
    document's current hash, and an equal hash appends no history and enqueues no work.
  - Changed bytes append a new immutable version; older versions are never edited or deleted.
  - A source-side deletion becomes a tombstone, not a row removal, so provenance survives.
  - A connector cursor advances only after every item on the fetched page has been durably
    versioned, recognised as an unchanged hash, or tombstoned. A crash mid-page replays the
    page rather than skipping it.
  - Document bytes, extracted text, source metadata, cursors, and secrets never reach audit
    metadata, telemetry attributes, or Oban job arguments. Those carry ids, hashes, counts,
    media types, and error classes only.

  ## Mistakes to avoid

  Connectors must not write knowledge or advance cursors early. Chunks and embeddings are derived;
  exports omit them and imports rebuild them with the destination embedder.
  """

  use Ash.Domain

  resources do
    resource MemHouse.Documents.ConnectorConfig
    resource MemHouse.Documents.DocumentChunk
  end

  @doc """
  Stores one document payload and appends an immutable version when its content changed.

  `attrs` may use atom or string keys. `"scope_id"` and `"bytes"` are required; a missing one
  raises `KeyError`. `"external_id"` identifies the document within its connector (a random
  UUID is generated for a one-off upload), and `"connector_config_id"`, `"title"`,
  `"source_kind"`, `"source_uri"`, `"source_metadata"`, `"media_type"`, `"occurred_at"`, and
  `"owner_peer_id"` are optional.

  Returns `{:ok, %{status: :created | :unchanged, document: document, version: version}}`.
  `:unchanged` means the payload hashed to the document's current content hash, so no version
  was appended and no extraction job was queued.

  Failure modes: a blob-store error short-circuits and is returned as `{:error, reason}` before
  anything is written to the database. Past that point the durable writes use raising Ash
  calls, so an authorization or validation failure raises.
  """
  defdelegate ingest_bytes(actor, attrs), to: MemHouse.Documents.Service

  @doc """
  Parses, chunks, embeds, and extracts knowledge from one already-durable document version.

  This is the pipeline-internal half of ingest and normally runs from the queued extraction
  job, under a system actor with pipeline privileges, so a caller does not supply an actor.

  Returns `{:ok, version}` with the version's processing bookkeeping updated, or
  `{:error, reason}` after recording the failure as an error *class* on the version. A failure
  leaves the version, its blob, its audit entry, and its retryable job intact, so the work can
  be attempted again without re-ingesting the bytes.
  """
  defdelegate process_version_for_account(version_id, account_id), to: MemHouse.Documents.Service

  @doc """
  Creates a connector configuration, audits it, and queues its first sync.

  `attrs` requires `"scope_id"`, `"name"`, and `"kind"` (the adapter key registered in
  application configuration); `"schedule_seconds"`, `"config"`, `"secret_ref"`, `"cursor"`,
  `"status"`, and `"next_sync_at"` are optional. A validation rejects `"config"` keys whose
  names look like credentials, and requires `"secret_ref"` to be a scheme-qualified reference
  such as an environment or vault URI.

  Returns the created connector. Raises on an authorization or validation failure.
  """
  defdelegate register_connector(actor, attrs), to: MemHouse.Documents.Service

  @doc """
  Queues a sync job for every active connector in the Account whose next-sync time has arrived.

  Connectors with no next-sync time are treated as due. Returns the list of enqueue results,
  one per connector.
  """
  defdelegate enqueue_due_connectors(account_id), to: MemHouse.Documents.Service

  @doc """
  Pulls one page from a connector's adapter, applies every item, and only then moves the cursor.

  Returns `{:ok, %{connector: connector, counts: counts}}` where `counts` tallies created,
  unchanged, and tombstoned items. When the adapter reports more pages, a follow-up sync job is
  queued with the new cursor. An adapter error returns `{:error, reason}` after recording the
  error class and a backoff on the connector, leaving the cursor where it was so the same page
  is fetched again.
  """
  defdelegate sync_connector_for_account(connector_id, account_id),
    to: MemHouse.Documents.Service

  @doc """
  Marks a document as deleted at its source without destroying any history.

  The document row and all its versions survive; chunks are marked tombstoned and knowledge
  supported *only* by this document is retracted through governance. Knowledge that another
  source also supports stays active and retrievable.

  Returns the tombstoned document. Raises if the document is not visible to the actor.
  """
  defdelegate tombstone_document(actor, document_id), to: MemHouse.Documents.Service

  @doc """
  Regenerates the derived caches for one document version by re-running processing.

  Chunks, vectors, and extracted text are rebuildable, so this is the supported answer to a
  changed chunk geometry, a changed parser, or a re-embed under a new embedding identity. Same
  return shape and failure modes as `process_version_for_account/2`.
  """
  defdelegate rebuild_version_for_account(version_id, account_id), to: MemHouse.Documents.Service

  @doc """
  Exports one document as a self-contained bundle of metadata plus checksum-verified bytes.

  Returns `{:ok, bundle}`. Derived chunks and embeddings are deliberately excluded; import
  rebuilds them. Raises if a stored blob no longer hashes to the digest its version recorded.
  """
  defdelegate export_document(actor, document_id), to: MemHouse.Documents.Portability

  @doc """
  Restores an exported document by replaying each version through ordinary ingest.

  Returns `{:ok, results}` in version order, or `{:error, :unsupported_document_bundle}` when
  the bundle's schema string is not one this build understands. Raises `ArgumentError` if a
  blob does not match its recorded checksum.
  """
  defdelegate import_document(actor, bundle), to: MemHouse.Documents.Portability

  @doc """
  Permanently removes a document, its versions, its chunks, and any blob only it referenced.

  Knowledge supported solely by this document is erased; knowledge with surviving provenance is
  kept and merely loses this document's provenance rows. Content-safe audit evidence of the
  erasure remains.

  Returns `:ok`. Raises `Ash.Error.Forbidden` unless the caller is the document owner, a
  curator, an account admin, or the pipeline.
  """
  defdelegate erase_document(actor, document_id), to: MemHouse.Documents.Portability
end

defmodule MemHouse.Documents.Validations.ContentSafeConnectorConfig do
  @moduledoc """
  Keeps raw credentials out of the connector configuration column.

  A connector row is ordinary Account data: it is read by operators and it travels verbatim in
  a logical Account export. A password or bearer token pasted into its settings map would
  therefore leak far beyond the sync job that needs it. This validation refuses that at the
  write boundary and forces the indirection instead — the row stores a *reference*
  (`env:SOME_VAR`, `vault://path/to/key`) for an adapter to resolve when it runs.

  Two independent checks run:

  - the settings map is walked recursively, including nested maps and lists, and any key whose
    name looks like a secret is rejected regardless of the value it holds;
  - a supplied secret reference must be scheme-qualified, so an operator cannot sidestep the
    first check by pasting the secret itself into the reference field.

  Key matching is deliberately fuzzy about punctuation and case: `apiKey`, `API_KEY`, and
  `api-key` all normalise to the same denied name. Adding a new secret-ish field name to a
  connector adapter means adding it to the denylist here too.
  """

  use Ash.Resource.Validation

  # Denied key names, already normalised to lowercase with "-" and "_" removed. Incoming keys
  # are normalised the same way before comparison, so one entry covers every spelling variant.
  @raw_secret_keys ~w(
    apikey authorization clientsecret credential credentials password privatekey
    secret token accesstoken refreshtoken authtoken bearer
  )
  # A scheme-qualified, whitespace-free reference: a lowercase scheme, a colon, then a locator.
  # This is a shape check, not a resolver — it only proves the operator supplied an indirection
  # rather than a literal secret.
  @secret_ref_regex ~r/\A[a-z][a-z0-9+.-]*:[^\s]+\z/

  @doc """
  Rejects raw secrets in the settings map and malformed secret references.

  Returns `:ok`, or `{:error, field: field, message: message}` naming the offending attribute.
  A `nil` settings map and a `nil` secret reference both pass.
  """
  @impl true
  def validate(changeset, _opts, _context) do
    config = Ash.Changeset.get_attribute(changeset, :config) || %{}
    secret_ref = Ash.Changeset.get_attribute(changeset, :secret_ref)

    cond do
      contains_secret?(config) ->
        {:error, field: :config, message: "must contain secret references, not raw secrets"}

      is_binary(secret_ref) and not Regex.match?(@secret_ref_regex, secret_ref) ->
        {:error, field: :secret_ref, message: "must be a scheme-qualified secret reference"}

      true ->
        :ok
    end
  end

  # Recursive because adapter settings nest: a credential is just as leaked one level down. Keys
  # are judged, not values — a value cannot be inspected for "secretness" reliably, whereas a
  # field named "token" is a token whatever it currently contains.
  defp contains_secret?(map) when is_map(map) do
    Enum.any?(map, fn {key, value} ->
      normalized =
        key
        |> to_string()
        |> String.downcase()
        |> String.replace(~r/[-_]/, "")

      normalized in @raw_secret_keys || contains_secret?(value)
    end)
  end

  defp contains_secret?(list) when is_list(list), do: Enum.any?(list, &contains_secret?/1)
  defp contains_secret?(_value), do: false
end

defmodule MemHouse.Documents.ConnectorConfig do
  @moduledoc """
  One configured external document source: what to sync, how often, and how far it has got.

  A row is durable authored state, not a cache. It names the adapter kind, the scope new
  documents land in, the owning peer, the polling interval, and the opaque cursor the adapter
  uses to resume. Losing this row loses sync progress, so it is exported and backed up like any
  other system-of-record data.

  ## The cursor is progress, not a hint

  `cursor` records the point past which the source has been fully handled. It moves only
  through the pipeline-only `advance_cursor` action, and only after every item on the fetched
  page has been durably versioned, recognised as an unchanged content hash, or tombstoned. A
  crash before that update replays the same page on the next run — repeated work is cheap
  because identical bytes are a no-op, whereas a prematurely advanced cursor silently skips
  documents forever.

  ## Content safety

  `config` holds adapter settings and `secret_ref` holds a reference such as an environment or
  vault URI. Settings keys whose names look like credentials are rejected on write. Neither
  column, nor the cursor, may be copied into audit metadata, telemetry, or job arguments; sync
  audit records counts and ids, and the sync job carries a hash of the cursor rather than the
  cursor itself.

  Failures are recorded as an error *class* plus a consecutive-failure count, never a provider
  message, and they push the next scheduled sync out by one interval.
  """

  use MemHouse.Resource,
    domain: MemHouse.Documents,
    table: "connector_configs"

  # Every read and write is filtered to the actor's Account by the tenant attribute, which
  # Postgres row-level security enforces a second time underneath.
  multitenancy do
    strategy :attribute
    attribute :account_id
  end

  actions do
    read :read do
      primary? true
    end

    # Registration. The settings map is checked for credential-looking key names and the secret
    # reference for a scheme prefix; status is restricted to the two values the due-connector
    # sweep understands.
    create :create do
      accept [
        :scope_id,
        :owner_peer_id,
        :name,
        :kind,
        :schedule_seconds,
        :config,
        :secret_ref,
        :cursor,
        :status,
        :next_sync_at
      ]

      validate MemHouse.Documents.Validations.ContentSafeConnectorConfig
      validate attribute_in(:status, ~w(active paused))
    end

    # Operator edits. Deliberately cannot touch the cursor: rewinding or skipping sync progress
    # by hand would either duplicate work or lose documents silently.
    update :update_config do
      accept [:name, :schedule_seconds, :config, :secret_ref, :status, :next_sync_at]
      require_atomic? false
      validate MemHouse.Documents.Validations.ContentSafeConnectorConfig
      validate attribute_in(:status, ~w(active paused))
    end

    # The commit point of one sync run: cursor, schedule, and failure bookkeeping. Pipeline-only.
    # A successful run reaches it after the whole page has been durably handled; a failed pull
    # reaches it too, writing the error class and backoff while leaving the cursor unchanged.
    update :advance_cursor do
      accept [
        :cursor,
        :next_sync_at,
        :last_synced_at,
        :last_error_class,
        :consecutive_failures
      ]

      require_atomic? false
    end

    destroy :erase do
      require_atomic? false
    end
  end

  policies do
    # Cross-Account isolation, checked before anything else. The Account comes from the
    # authenticated actor, never from a request parameter.
    policy always() do
      authorize_if expr(account_id == ^actor(:account_id))
    end

    policy action_type(:read) do
      authorize_if {MemHouse.Policy.ScopeAccess, attribute: :scope_id}
    end

    # Registering or reconfiguring a source is administrative work: it must be an authenticated
    # human holding an admin or curator grant in that scope. A machine credential cannot do it,
    # even one that may submit observations. The pipeline branch covers internal maintenance.
    policy action([:create, :update_config, :erase]) do
      authorize_if {MemHouse.Policy.HumanScopeRole, roles: [:account_admin, :curator]}
      authorize_if actor_attribute_equals(:pipeline?, true)
    end

    policy action(:advance_cursor) do
      authorize_if actor_attribute_equals(:pipeline?, true)
    end
  end

  attributes do
    uuid_primary_key :id
    attribute :account_id, :uuid, allow_nil?: false

    # Where documents from this source land, and who is recorded as their observer.
    attribute :scope_id, :uuid, allow_nil?: false, public?: true
    attribute :owner_peer_id, :uuid, allow_nil?: false, public?: true
    attribute :name, :string, allow_nil?: false, public?: true

    # Adapter key looked up in application configuration. No adapters ship enabled, so a
    # deployment registers the ones it wants before a connector of that kind can sync.
    attribute :kind, :string, allow_nil?: false, public?: true

    # Polling interval in seconds; one hour by default. Also used as the backoff after a failed
    # run.
    attribute :schedule_seconds, :integer,
      allow_nil?: false,
      default: 3600,
      constraints: [min: 1],
      public?: true

    # Adapter settings and a credential *reference*. Both are non-public, so Ash-generated
    # interfaces do not serialise them. `config` is rejected on write when a key name looks
    # like a credential, and `secret_ref` must be scheme-qualified.
    attribute :config, :map, allow_nil?: false, default: %{}
    attribute :secret_ref, :string

    # Opaque, adapter-defined resume point. Non-public and never logged.
    attribute :cursor, :map, allow_nil?: false, default: %{}

    # "active" or "paused". Only active connectors are picked up by the due-connector sweep.
    attribute :status, :string, allow_nil?: false, default: "active", public?: true
    attribute :next_sync_at, :utc_datetime_usec, public?: true
    attribute :last_synced_at, :utc_datetime_usec, public?: true

    # An error class name, never a provider message, so operators can see a source is broken
    # without the failure text leaking source content.
    attribute :last_error_class, :string, public?: true
    attribute :consecutive_failures, :integer, allow_nil?: false, default: 0, public?: true
    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  # Connector names are unique within a scope, so operators can refer to a source by name and
  # a repeated registration collides instead of quietly creating a second poller.
  identities do
    identity :scope_name, [:scope_id, :name]
  end
end

defmodule MemHouse.Documents.DocumentChunk do
  @moduledoc """
  One retrievable slice of one immutable document version, together with its embedding.

  A chunk row is a **derived cache**: text, byte range, hash, and vector are all reproducible
  by re-reading the version's blob and re-running the parser, chunker, and embedder. Nothing
  here is a system of record. That is why chunks are excluded from logical exports, why erasure
  can delete them outright, and why changing chunk geometry or swapping embedding models is a
  rebuild rather than a migration.

  ## Rebuild safety

  Chunks are keyed by version plus position and written through an upsert, so re-processing the
  same version overwrites in place instead of accumulating duplicates. That is what makes the
  extraction job safe to retry.

  When a document changes, chunks belonging to older versions are marked superseded rather than
  deleted, and when a document is tombstoned its chunks are marked tombstoned. Retrieval filters
  on that status, so stale text stops being findable without history being destroyed.

  ## Embedding identity

  Every row pins the provider, model, model version, and dimension count that produced its
  vector. Vectors from different identities are not comparable, so a mismatch must go through
  an explicit re-embed; never reuse or silently substitute a vector whose identity differs.

  ## Exposure

  The chunk text, its content hash, and its vector are non-public attributes, so Ash-generated
  interfaces do not serialise them. That is not the same as unreachable: retrieval queries this
  table with its own SQL, and a search result for a matching chunk carries the chunk text to
  callers authorized for its scope.
  """

  use MemHouse.Resource,
    domain: MemHouse.Documents,
    table: "document_chunks"

  # Account isolation on every query, backed again by Postgres row-level security.
  multitenancy do
    strategy :attribute
    attribute :account_id
  end

  actions do
    read :read do
      primary? true
    end

    # Pipeline-only write. The upsert on (version, position) is what makes re-processing a
    # version idempotent: a retried or replayed job rewrites the same rows rather than
    # duplicating them. Every derived value is in the upsert field list, so a rebuild under a
    # new chunker or embedder rewrites the rows it touches — nothing here removes rows at
    # positions the rebuild no longer produces.
    create :upsert_from_pipeline do
      accept [
        :document_id,
        :document_version_id,
        :scope_id,
        :position,
        :start_byte,
        :end_byte,
        :text,
        :content_hash,
        :embedding,
        :embedding_provider,
        :embedding_model,
        :embedding_version,
        :embedding_dimensions,
        :status
      ]

      upsert? true
      upsert_identity :version_position

      upsert_fields [
        :start_byte,
        :end_byte,
        :text,
        :content_hash,
        :embedding,
        :embedding_provider,
        :embedding_model,
        :embedding_version,
        :embedding_dimensions,
        :status,
        :updated_at
      ]
    end

    update :reindex_from_pipeline do
      accept [
        :embedding,
        :embedding_provider,
        :embedding_model,
        :embedding_version,
        :embedding_dimensions
      ]

      require_atomic? false
    end

    # Retires a chunk without deleting it: "superseded" when a newer version of the document
    # arrived, "tombstoned" when the source document was deleted. Retrieval filters on status.
    update :supersede do
      accept [:status]
      require_atomic? false
    end

    destroy :erase do
      require_atomic? false
    end
  end

  policies do
    policy always() do
      authorize_if expr(account_id == ^actor(:account_id))
    end

    # Reads are additionally filtered to scopes the actor may see, so a chunk never surfaces
    # document text from a scope the caller has no access to.
    policy action_type(:read) do
      authorize_if {MemHouse.Policy.ScopeAccess, attribute: :scope_id}
    end

    # No human or machine caller writes chunks. They exist only as a by-product of processing a
    # document version, and must stay consistent with the version they were derived from.
    policy action_type([:create, :update, :destroy]) do
      authorize_if actor_attribute_equals(:pipeline?, true)
    end
  end

  attributes do
    uuid_primary_key :id
    attribute :account_id, :uuid, allow_nil?: false

    # The version is the chunk's real parent; the document id is denormalised so tombstoning
    # and erasure can sweep every chunk of a document without joining through versions.
    attribute :document_id, :uuid, allow_nil?: false, public?: true
    attribute :document_version_id, :uuid, allow_nil?: false, public?: true
    attribute :scope_id, :uuid, allow_nil?: false, public?: true

    # Zero-based order within the version, and the byte range of the extracted text this chunk
    # covers.
    attribute :position, :integer, allow_nil?: false, public?: true
    attribute :start_byte, :integer, allow_nil?: false, public?: true
    attribute :end_byte, :integer, allow_nil?: false, public?: true

    # Document content. Non-public, so Ash-generated interfaces do not serialise it; retrieval
    # reads it with its own SQL.
    attribute :text, :string, allow_nil?: false
    attribute :content_hash, :string, allow_nil?: false
    attribute :embedding, :vector, allow_nil?: false

    # The pinned identity of the model that produced the vector above. Vectors from different
    # identities are not comparable, so a mismatch means re-embedding, never substituting.
    attribute :embedding_provider, :string, allow_nil?: false, public?: true
    attribute :embedding_model, :string, allow_nil?: false, public?: true
    attribute :embedding_version, :string, allow_nil?: false, public?: true
    attribute :embedding_dimensions, :integer, allow_nil?: false, public?: true

    # "active", "superseded", or "tombstoned".
    attribute :status, :string, allow_nil?: false, default: "active", public?: true
    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  # The upsert key. One chunk per position per version, which is what makes re-processing a
  # version overwrite rather than duplicate.
  identities do
    identity :version_position, [:document_version_id, :position]
  end
end
