defmodule MemHouse.Repo.Migrations.Issue178ExtractionClaimFence do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pipeline_runs) do
      add :batch_claim_id, :uuid
    end
  end

  def down do
    alter table(:pipeline_runs) do
      remove :batch_claim_id
    end
  end
end
