# SPDX-License-Identifier: MemHouse-Sustainable-Use-1.0

defmodule MemHouse.Repo.Migrations.F1AshDomainBackbone do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @account_tables ~w(
    attributions audit_events document_versions documents entities entity_mentions
    external_identities knowledge_items knowledge_lifecycle_events knowledge_relations
    messages model_role_configs peers policy_configs projections provenances retrieval_profiles
    role_grants scope_relations scopes session_participants session_scopes sessions
    skill_requirement_cards usage_events
  )

  @foreign_keys [
    {"usage_events", "account_id", "accounts", "CASCADE"},
    {"usage_events", "scope_id", "scopes", "SET NULL"},
    {"usage_events", "peer_id", "peers", "SET NULL"},
    {"skill_requirement_cards", "account_id", "accounts", "CASCADE"},
    {"skill_requirement_cards", "scope_id", "scopes", "CASCADE"},
    {"session_scopes", "account_id", "accounts", "CASCADE"},
    {"session_scopes", "session_id", "sessions", "CASCADE"},
    {"session_scopes", "scope_id", "scopes", "CASCADE"},
    {"session_participants", "account_id", "accounts", "CASCADE"},
    {"session_participants", "session_id", "sessions", "CASCADE"},
    {"session_participants", "peer_id", "peers", "CASCADE"},
    {"scope_relations", "account_id", "accounts", "CASCADE"},
    {"scope_relations", "source_scope_id", "scopes", "CASCADE"},
    {"scope_relations", "target_scope_id", "scopes", "CASCADE"},
    {"role_grants", "account_id", "accounts", "CASCADE"},
    {"role_grants", "scope_id", "scopes", "CASCADE"},
    {"role_grants", "peer_id", "peers", "CASCADE"},
    {"retrieval_profiles", "account_id", "accounts", "CASCADE"},
    {"retrieval_profiles", "scope_id", "scopes", "CASCADE"},
    {"provenances", "account_id", "accounts", "CASCADE"},
    {"provenances", "knowledge_item_id", "knowledge_items", "CASCADE"},
    {"provenances", "scope_id", "scopes", "CASCADE"},
    {"provenances", "message_id", "messages", "SET NULL"},
    {"provenances", "document_version_id", "document_versions", "SET NULL"},
    {"projections", "account_id", "accounts", "CASCADE"},
    {"projections", "scope_id", "scopes", "CASCADE"},
    {"projections", "peer_id", "peers", "CASCADE"},
    {"projections", "session_id", "sessions", "CASCADE"},
    {"policy_configs", "account_id", "accounts", "CASCADE"},
    {"policy_configs", "scope_id", "scopes", "CASCADE"},
    {"peers", "default_scope_id", "scopes", "SET NULL"},
    {"model_role_configs", "account_id", "accounts", "CASCADE"},
    {"model_role_configs", "scope_id", "scopes", "CASCADE"},
    {"knowledge_relations", "account_id", "accounts", "CASCADE"},
    {"knowledge_relations", "scope_id", "scopes", "CASCADE"},
    {"knowledge_relations", "source_knowledge_id", "knowledge_items", "CASCADE"},
    {"knowledge_relations", "target_knowledge_id", "knowledge_items", "CASCADE"},
    {"knowledge_lifecycle_events", "scope_id", "scopes", "CASCADE"},
    {"external_identities", "account_id", "accounts", "CASCADE"},
    {"external_identities", "peer_id", "peers", "CASCADE"},
    {"entity_mentions", "account_id", "accounts", "CASCADE"},
    {"entity_mentions", "knowledge_item_id", "knowledge_items", "CASCADE"},
    {"entity_mentions", "scope_id", "scopes", "CASCADE"},
    {"entity_mentions", "entity_id", "entities", "CASCADE"},
    {"entities", "account_id", "accounts", "CASCADE"},
    {"documents", "account_id", "accounts", "CASCADE"},
    {"documents", "scope_id", "scopes", "CASCADE"},
    {"documents", "owner_peer_id", "peers", "SET NULL"},
    {"documents", "current_version_id", "document_versions", "SET NULL"},
    {"document_versions", "account_id", "accounts", "CASCADE"},
    {"document_versions", "document_id", "documents", "CASCADE"},
    {"document_versions", "scope_id", "scopes", "CASCADE"},
    {"audit_events", "account_id", "accounts", "CASCADE"},
    {"audit_events", "scope_id", "scopes", "SET NULL"},
    {"audit_events", "actor_peer_id", "peers", "SET NULL"},
    {"attributions", "account_id", "accounts", "CASCADE"},
    {"attributions", "knowledge_item_id", "knowledge_items", "CASCADE"},
    {"attributions", "scope_id", "scopes", "CASCADE"},
    {"attributions", "target_peer_id", "peers", "SET NULL"},
    {"attributions", "target_scope_id", "scopes", "SET NULL"}
  ]

  def up do
    execute "CREATE EXTENSION IF NOT EXISTS pgcrypto"
    execute "CREATE EXTENSION IF NOT EXISTS vector"

    create table(:usage_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :scope_id, :uuid
      add :peer_id, :uuid
      add :operation, :text, null: false
      add :model_role, :text
      add :model_name, :text
      add :input_tokens, :bigint, null: false, default: 0
      add :output_tokens, :bigint, null: false, default: 0
      add :duration_ms, :bigint, null: false, default: 0
      add :metadata, :map, null: false, default: %{}
      add :occurred_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:skill_requirement_cards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :skill_key, :text, null: false
      add :version, :bigint, null: false
      add :requirements, {:array, :map}, null: false, default: []
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:skill_requirement_cards, [:account_id, :scope_id, :skill_key, :version],
             name: "skill_requirement_cards_scope_skill_version_index"
           )

    alter table(:sessions) do
      add :opened_at, :utc_datetime_usec
      add :closed_at, :utc_datetime_usec
    end

    execute "ALTER INDEX sessions_account_id_external_id_index RENAME TO sessions_external_id_index"

    create table(:session_scopes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :session_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :classification, :text, null: false, default: "tentative"
      add :confirmed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:session_scopes, [:account_id, :session_id, :scope_id],
             name: "session_scopes_session_scope_index"
           )

    create table(:session_participants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :session_id, :uuid, null: false
      add :peer_id, :uuid, null: false
      add :role, :text, null: false, default: "participant"
      add :joined_at, :utc_datetime_usec, null: false
      add :left_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:session_participants, [:account_id, :session_id, :peer_id],
             name: "session_participants_session_peer_index"
           )

    alter table(:scopes) do
      add :state, :text, null: false, default: "active"
    end

    execute "ALTER INDEX scopes_account_id_path_index RENAME TO scopes_unique_path_index"

    create table(:scope_relations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :source_scope_id, :uuid, null: false
      add :target_scope_id, :uuid, null: false
      add :kind, :text, null: false, default: "related"
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(
             :scope_relations,
             [:account_id, :source_scope_id, :target_scope_id, :kind],
             name: "scope_relations_unique_relation_index"
           )

    create table(:role_grants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :peer_id, :uuid, null: false
      add :role, :text, null: false
      add :propagate, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:role_grants, [:account_id, :scope_id, :peer_id],
             name: "role_grants_unique_grant_index"
           )

    create table(:retrieval_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :scope_id, :uuid
      add :name, :text, null: false
      add :version, :bigint, null: false
      add :strategy_config, :map, null: false, default: %{}
      add :deadline_ms, :bigint, null: false
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:retrieval_profiles, [:account_id, :scope_id, :name, :version],
             name: "retrieval_profiles_scope_name_version_index"
           )

    create table(:provenances, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :knowledge_item_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :source_type, :text, null: false
      add :message_id, :uuid
      add :document_version_id, :uuid
      add :extracting_model, :text
      add :pipeline_version, :text, null: false
      add :occurred_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:projections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :peer_id, :uuid
      add :session_id, :uuid
      add :kind, :text, null: false
      add :version, :bigint, null: false, default: 1
      add :content, :map, null: false, default: %{}
      add :source_ids, {:array, :uuid}, null: false, default: []
      add :dirty, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:policy_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :scope_id, :uuid
      add :key, :text, null: false
      add :value, :map, null: false, default: %{}
      add :version, :bigint, null: false, default: 1
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:policy_configs, [:account_id, :scope_id, :key, :version],
             name: "policy_configs_scope_key_version_index"
           )

    alter table(:peers) do
      add :default_scope_id, :uuid
    end

    execute "ALTER INDEX peers_account_id_key_index RENAME TO peers_unique_key_index"

    create table(:model_role_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :scope_id, :uuid
      add :role, :text, null: false
      add :provider, :text, null: false
      add :model, :text, null: false
      add :options, :map, null: false, default: %{}
      add :version, :bigint, null: false, default: 1
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:model_role_configs, [:account_id, :scope_id, :role, :version],
             name: "model_role_configs_scope_role_version_index"
           )

    create table(:knowledge_relations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :source_knowledge_id, :uuid, null: false
      add :target_knowledge_id, :uuid, null: false
      add :kind, :text, null: false
      add :confidence, :float, null: false, default: 1.0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(
             :knowledge_relations,
             [:account_id, :source_knowledge_id, :target_knowledge_id, :kind],
             name: "knowledge_relations_unique_relation_index"
           )

    alter table(:knowledge_lifecycle_events) do
      add :scope_id, :uuid
    end

    execute """
    UPDATE knowledge_lifecycle_events AS event
    SET scope_id = knowledge.scope_id
    FROM knowledge_items AS knowledge
    WHERE knowledge.id = event.knowledge_item_id
    """

    alter table(:knowledge_lifecycle_events) do
      modify :scope_id, :uuid, null: false
    end

    create table(:external_identities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :peer_id, :uuid, null: false
      add :provider, :text, null: false
      add :subject, :text, null: false
      add :email, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:external_identities, [:account_id, :provider, :subject],
             name: "external_identities_provider_subject_index"
           )

    create table(:entity_mentions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :knowledge_item_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :entity_id, :uuid, null: false
      add :surface_form, :text, null: false
      add :confidence, :float, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(
             :entity_mentions,
             [:account_id, :knowledge_item_id, :entity_id, :surface_form],
             name: "entity_mentions_knowledge_entity_surface_index"
           )

    create table(:entities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :canonical_name, :text, null: false
      add :kind, :text, null: false
      add :aliases, {:array, :text}, null: false, default: []
      add :derived_from, {:array, :uuid}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:entities, [:account_id, :canonical_name, :kind],
             name: "entities_canonical_name_kind_index"
           )

    create table(:documents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :owner_peer_id, :uuid
      add :current_version_id, :uuid
      add :external_id, :text
      add :title, :text, null: false
      add :source_kind, :text, null: false, default: "upload"
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:documents, [:account_id, :external_id],
             name: "documents_external_id_index"
           )

    create table(:document_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :document_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :version, :bigint, null: false
      add :content, :text, null: false
      add :content_hash, :text, null: false
      add :media_type, :text, null: false, default: "text/plain"
      add :occurred_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:document_versions, [:account_id, :document_id, :content_hash],
             name: "document_versions_document_hash_index"
           )

    create unique_index(:document_versions, [:account_id, :document_id, :version],
             name: "document_versions_document_version_index"
           )

    create table(:audit_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :scope_id, :uuid
      add :actor_peer_id, :uuid
      add :action, :text, null: false
      add :resource_type, :text, null: false
      add :resource_id, :uuid
      add :metadata, :map, null: false, default: %{}
      add :previous_hash, :text
      add :event_hash, :text, null: false
      add :occurred_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:attributions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :knowledge_item_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :target_type, :text, null: false
      add :target_peer_id, :uuid
      add :target_scope_id, :uuid
      add :level, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(
             :attributions,
             [
               :account_id,
               :knowledge_item_id,
               :target_type,
               :target_peer_id,
               :target_scope_id,
               :level
             ],
             name: "attributions_knowledge_target_index"
           )

    execute "ALTER INDEX accounts_key_index RENAME TO accounts_unique_key_index"

    install_foreign_keys()
    install_indexes_and_fts()
    install_rls()
  end

  def down do
    remove_rls()
    remove_indexes_and_fts()
    remove_foreign_keys()

    execute "ALTER INDEX accounts_unique_key_index RENAME TO accounts_key_index"

    drop_if_exists unique_index(
                     :attributions,
                     [
                       :account_id,
                       :knowledge_item_id,
                       :target_type,
                       :target_peer_id,
                       :target_scope_id,
                       :level
                     ],
                     name: "attributions_knowledge_target_index"
                   )

    drop table(:attributions)

    drop table(:audit_events)

    drop_if_exists unique_index(:document_versions, [:account_id, :document_id, :version],
                     name: "document_versions_document_version_index"
                   )

    drop_if_exists unique_index(:document_versions, [:account_id, :document_id, :content_hash],
                     name: "document_versions_document_hash_index"
                   )

    drop table(:document_versions)

    drop_if_exists unique_index(:documents, [:account_id, :external_id],
                     name: "documents_external_id_index"
                   )

    drop table(:documents)

    drop_if_exists unique_index(:entities, [:account_id, :canonical_name, :kind],
                     name: "entities_canonical_name_kind_index"
                   )

    drop table(:entities)

    drop_if_exists unique_index(
                     :entity_mentions,
                     [:account_id, :knowledge_item_id, :entity_id, :surface_form],
                     name: "entity_mentions_knowledge_entity_surface_index"
                   )

    drop table(:entity_mentions)

    drop_if_exists unique_index(:external_identities, [:account_id, :provider, :subject],
                     name: "external_identities_provider_subject_index"
                   )

    drop table(:external_identities)

    alter table(:knowledge_lifecycle_events) do
      remove :scope_id
    end

    drop_if_exists unique_index(
                     :knowledge_relations,
                     [:account_id, :source_knowledge_id, :target_knowledge_id, :kind],
                     name: "knowledge_relations_unique_relation_index"
                   )

    drop table(:knowledge_relations)

    drop_if_exists unique_index(:model_role_configs, [:account_id, :scope_id, :role, :version],
                     name: "model_role_configs_scope_role_version_index"
                   )

    drop table(:model_role_configs)

    execute "ALTER INDEX peers_unique_key_index RENAME TO peers_account_id_key_index"

    alter table(:peers) do
      remove :default_scope_id
    end

    drop_if_exists unique_index(:policy_configs, [:account_id, :scope_id, :key, :version],
                     name: "policy_configs_scope_key_version_index"
                   )

    drop table(:policy_configs)

    drop table(:projections)

    drop table(:provenances)

    drop_if_exists unique_index(:retrieval_profiles, [:account_id, :scope_id, :name, :version],
                     name: "retrieval_profiles_scope_name_version_index"
                   )

    drop table(:retrieval_profiles)

    drop_if_exists unique_index(:role_grants, [:account_id, :scope_id, :peer_id],
                     name: "role_grants_unique_grant_index"
                   )

    drop table(:role_grants)

    drop_if_exists unique_index(
                     :scope_relations,
                     [:account_id, :source_scope_id, :target_scope_id, :kind],
                     name: "scope_relations_unique_relation_index"
                   )

    drop table(:scope_relations)

    execute "ALTER INDEX scopes_unique_path_index RENAME TO scopes_account_id_path_index"

    alter table(:scopes) do
      remove :state
    end

    drop_if_exists unique_index(:session_participants, [:account_id, :session_id, :peer_id],
                     name: "session_participants_session_peer_index"
                   )

    drop table(:session_participants)

    drop_if_exists unique_index(:session_scopes, [:account_id, :session_id, :scope_id],
                     name: "session_scopes_session_scope_index"
                   )

    drop table(:session_scopes)

    execute "ALTER INDEX sessions_external_id_index RENAME TO sessions_account_id_external_id_index"

    alter table(:sessions) do
      remove :closed_at
      remove :opened_at
    end

    drop_if_exists unique_index(
                     :skill_requirement_cards,
                     [:account_id, :scope_id, :skill_key, :version],
                     name: "skill_requirement_cards_scope_skill_version_index"
                   )

    drop table(:skill_requirement_cards)

    drop table(:usage_events)
  end

  defp install_foreign_keys do
    Enum.each(@foreign_keys, fn {table_name, column, target, on_delete} ->
      execute """
      ALTER TABLE #{table_name}
      ADD CONSTRAINT #{table_name}_#{column}_fkey
      FOREIGN KEY (#{column}) REFERENCES #{target}(id) ON DELETE #{on_delete}
      """
    end)
  end

  defp remove_foreign_keys do
    Enum.each(Enum.reverse(@foreign_keys), fn {table_name, column, _target, _on_delete} ->
      execute "ALTER TABLE #{table_name} DROP CONSTRAINT IF EXISTS #{table_name}_#{column}_fkey"
    end)
  end

  defp install_indexes_and_fts do
    Enum.each(@account_tables, fn table_name ->
      execute "CREATE INDEX IF NOT EXISTS #{table_name}_account_id_index ON #{table_name} (account_id)"
    end)

    execute """
    ALTER TABLE document_versions
    ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (to_tsvector('english', coalesce(content, ''))) STORED
    """

    execute """
    CREATE INDEX document_versions_search_vector_idx
    ON document_versions USING GIN (search_vector)
    """

    execute "CREATE INDEX scope_relations_target_scope_id_index ON scope_relations (target_scope_id)"
    execute "CREATE INDEX provenances_message_id_index ON provenances (message_id)"

    execute """
    CREATE INDEX knowledge_lifecycle_events_occurred_at_index
    ON knowledge_lifecycle_events (account_id, occurred_at)
    """
  end

  defp remove_indexes_and_fts do
    execute "DROP INDEX IF EXISTS knowledge_lifecycle_events_occurred_at_index"
    execute "DROP INDEX IF EXISTS provenances_message_id_index"
    execute "DROP INDEX IF EXISTS scope_relations_target_scope_id_index"
    execute "DROP INDEX IF EXISTS document_versions_search_vector_idx"
    execute "ALTER TABLE document_versions DROP COLUMN IF EXISTS search_vector"

    Enum.each(@account_tables, fn table_name ->
      execute "DROP INDEX IF EXISTS #{table_name}_account_id_index"
    end)
  end

  defp install_rls do
    execute "ALTER TABLE accounts ENABLE ROW LEVEL SECURITY"
    execute "ALTER TABLE accounts FORCE ROW LEVEL SECURITY"

    execute """
    CREATE POLICY cartulary_account_wall ON accounts
    USING (
      id = NULLIF(current_setting('memhouse.account_id', true), '')::uuid
      OR key = NULLIF(current_setting('memhouse.account_key', true), '')
    )
    WITH CHECK (
      id = NULLIF(current_setting('memhouse.account_id', true), '')::uuid
      OR key = NULLIF(current_setting('memhouse.account_key', true), '')
    )
    """

    Enum.each(@account_tables, fn table_name ->
      execute "ALTER TABLE #{table_name} ENABLE ROW LEVEL SECURITY"
      execute "ALTER TABLE #{table_name} FORCE ROW LEVEL SECURITY"

      execute """
      CREATE POLICY cartulary_account_wall ON #{table_name}
      USING (
        account_id = NULLIF(current_setting('memhouse.account_id', true), '')::uuid
      )
      WITH CHECK (
        account_id = NULLIF(current_setting('memhouse.account_id', true), '')::uuid
      )
      """
    end)
  end

  defp remove_rls do
    Enum.each(Enum.reverse(@account_tables), fn table_name ->
      execute "DROP POLICY IF EXISTS cartulary_account_wall ON #{table_name}"
      execute "ALTER TABLE #{table_name} NO FORCE ROW LEVEL SECURITY"
      execute "ALTER TABLE #{table_name} DISABLE ROW LEVEL SECURITY"
    end)

    execute "DROP POLICY IF EXISTS cartulary_account_wall ON accounts"
    execute "ALTER TABLE accounts NO FORCE ROW LEVEL SECURITY"
    execute "ALTER TABLE accounts DISABLE ROW LEVEL SECURITY"
  end
end
