defmodule MemHouse.Repo.Migrations.Issue204DreamTimeWatermarks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:dream_time_watermarks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :input_watermark, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:dream_time_watermarks, [:account_id, :scope_id],
             name: "dream_time_watermarks_scope_index"
           )

    # Progress is Account-owned operational state. Ash multitenancy is backed
    # by this RLS wall so a pooled background connection cannot read another
    # Account's watermark before the pipeline declares its Account.
    execute "ALTER TABLE dream_time_watermarks ENABLE ROW LEVEL SECURITY"
    execute "ALTER TABLE dream_time_watermarks FORCE ROW LEVEL SECURITY"

    execute """
    CREATE POLICY memhouse_account_wall ON dream_time_watermarks
    USING (account_id = current_setting('memhouse.account_id', true)::uuid)
    WITH CHECK (account_id = current_setting('memhouse.account_id', true)::uuid)
    """
  end

  def down do
    execute "DROP POLICY IF EXISTS memhouse_account_wall ON dream_time_watermarks"

    drop_if_exists unique_index(:dream_time_watermarks, [:account_id, :scope_id],
                     name: "dream_time_watermarks_scope_index"
                   )

    drop table(:dream_time_watermarks)
  end
end
