defmodule MemHouse.Repo.Migrations.Issue206GovernedDeductions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:knowledge_items) do
      add :deduction_key, :text
      add :deduction_family_key, :text
      add :contributor_ids, {:array, :uuid}, null: false, default: []
    end

    create unique_index(:knowledge_items, [:account_id, :deduction_key],
             name: "knowledge_items_deduction_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:knowledge_items, [:account_id, :deduction_key],
                     name: "knowledge_items_deduction_key_index"
                   )

    alter table(:knowledge_items) do
      remove :contributor_ids
      remove :deduction_family_key
      remove :deduction_key
    end
  end
end
