defmodule MemHouse.Repo.Migrations.Issue174DeterministicGateAEvidence do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:knowledge_items) do
      add :evidence_level, :text, null: false, default: "indirect"
    end

    alter table(:governance_gate_rules) do
      add :minimum_evidence_level, :text, null: false, default: "direct"
    end
  end

  def down do
    alter table(:governance_gate_rules) do
      remove :minimum_evidence_level
    end

    alter table(:knowledge_items) do
      remove :evidence_level
    end
  end
end
