defmodule MemHouse.Repo.Migrations.Issue72EntityCards do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projections) do
      add :entity_id, :uuid
      add :sensitivity, :text
    end

    # Entity-card reads enumerate the clean cards in one Account/scope on every cold context
    # request. Keep that lookup off a full projection-table scan without indexing unrelated kinds.
    create index(:projections, [:account_id, :scope_id],
             name: "projections_clean_entity_cards_index",
             where: "kind = 'entity_card' AND dirty = false"
           )
  end

  def down do
    drop index(:projections, [:account_id, :scope_id],
           name: "projections_clean_entity_cards_index"
         )

    alter table(:projections) do
      remove :sensitivity
      remove :entity_id
    end
  end
end
