# SPDX-License-Identifier: MemHouse-Sustainable-Use-1.0

defmodule MemHouse.Repo.Migrations.F5ModelLayerStructuredExtraction do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:model_role_configs) do
      add :model_version, :text, null: false, default: "unversioned"
      add :prompt_version, :text, null: false, default: "none"
      add :pipeline_version, :text, null: false, default: "f5-1"
      add :embedding_dimensions, :bigint
    end

    alter table(:provenances) do
      add :extracting_provider, :text
      add :extracting_model_version, :text
      add :prompt_version, :text
      add :embedding_provider, :text
      add :embedding_model, :text
      add :embedding_version, :text
    end

    alter table(:knowledge_items) do
      modify :pipeline_version, :text, default: "f5-1"
      add :extracting_provider, :text
      add :extracting_model_version, :text
      add :prompt_version, :text
      add :embedding_provider, :text
      add :embedding_model, :text
      add :embedding_version, :text
    end

    execute """
    UPDATE usage_events
    SET model_name = COALESCE(model_name, 'legacy'),
        model_role = COALESCE(model_role, 'legacy')
    """

    alter table(:usage_events) do
      modify :model_name, :text, null: false
      modify :model_role, :text, null: false
      add :call_id, :uuid, null: false, default: fragment("gen_random_uuid()")
      add :provider, :text, null: false, default: "legacy"
      add :model_version, :text, null: false, default: "unversioned"
      add :prompt_version, :text, null: false, default: "none"
      add :pipeline_version, :text, null: false, default: "poc-0"
      add :embedding_tokens, :bigint, null: false, default: 0
      add :status, :text, null: false, default: "ok"
    end

    execute """
    ALTER TABLE usage_events
      ALTER COLUMN call_id DROP DEFAULT,
      ALTER COLUMN provider DROP DEFAULT,
      ALTER COLUMN model_version DROP DEFAULT,
      ALTER COLUMN prompt_version DROP DEFAULT,
      ALTER COLUMN pipeline_version DROP DEFAULT
    """

    create unique_index(:usage_events, [:account_id, :call_id],
             name: "usage_events_call_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:usage_events, [:account_id, :call_id],
                     name: "usage_events_call_id_index"
                   )

    alter table(:usage_events) do
      remove :status
      remove :embedding_tokens
      remove :pipeline_version
      remove :prompt_version
      remove :model_version
      remove :provider
      remove :call_id
      modify :model_role, :text, null: true
      modify :model_name, :text, null: true
    end

    alter table(:knowledge_items) do
      remove :embedding_version
      remove :embedding_model
      remove :embedding_provider
      remove :prompt_version
      remove :extracting_model_version
      remove :extracting_provider
      modify :pipeline_version, :text, default: "poc-0"
    end

    alter table(:provenances) do
      remove :embedding_version
      remove :embedding_model
      remove :embedding_provider
      remove :prompt_version
      remove :extracting_model_version
      remove :extracting_provider
    end

    alter table(:model_role_configs) do
      remove :embedding_dimensions
      remove :pipeline_version
      remove :prompt_version
      remove :model_version
    end
  end
end
