# SPDX-License-Identifier: MemHouse-Sustainable-Use-1.0

defmodule MemHouse.Repo.Migrations.F9SkillReadinessProceduralMemory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:skill_requirement_cards) do
      add :description, :text
      add :requirement_schema_version, :text, null: false, default: "f9-1"
    end
  end

  def down do
    alter table(:skill_requirement_cards) do
      remove :requirement_schema_version
      remove :description
    end
  end
end
