# SPDX-License-Identifier: MemHouse-Sustainable-Use-1.0

defmodule MemHouse.Repo.Migrations.F2TransactionalWritesAuditJobs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pipeline_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, references(:accounts, type: :uuid, on_delete: :delete_all), null: false
      add :scope_id, references(:scopes, type: :uuid, on_delete: :nilify_all)
      add :kind, :text, null: false
      add :target_type, :text, null: false
      add :target_id, :uuid
      add :idempotency_key, :text, null: false
      add :payload, :map, null: false, default: %{}
      add :status, :text, null: false, default: "pending"
      add :attempt_count, :bigint, null: false, default: 0
      add :processed_at, :utc_datetime_usec
      add :last_error_class, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:pipeline_runs, [:account_id, :idempotency_key],
             name: "pipeline_runs_idempotency_key_index"
           )

    create index(:pipeline_runs, [:account_id, :kind, :status],
             name: "pipeline_runs_reconciliation_index"
           )

    alter table(:messages) do
      add :content_hash, :text
      add :extraction_completed_at, :utc_datetime_usec
    end

    execute """
    UPDATE messages
    SET content_hash = encode(digest(content, 'sha256'), 'hex')
    WHERE content_hash IS NULL
    """

    alter table(:messages) do
      modify :content_hash, :text, null: false, from: :text
    end

    create index(:messages, [:account_id, :extraction_completed_at],
             name: "messages_extraction_reconciliation_index"
           )

    alter table(:knowledge_items) do
      add :statement_hash, :text
    end

    execute """
    UPDATE knowledge_items
    SET statement_hash = encode(digest(statement, 'sha256'), 'hex')
    WHERE statement_hash IS NULL
    """

    alter table(:knowledge_items) do
      modify :statement_hash, :text, null: false, from: :text
    end

    alter table(:audit_events) do
      add :category, :text
      add :content_hash, :text
    end

    execute "UPDATE audit_events SET category = 'governance' WHERE category IS NULL"

    alter table(:audit_events) do
      modify :category, :text, null: false, from: :text
    end

    create index(:audit_events, [:account_id, :inserted_at, :id],
             name: "audit_events_hash_chain_index"
           )

    execute "ALTER TABLE pipeline_runs ENABLE ROW LEVEL SECURITY"
    execute "ALTER TABLE pipeline_runs FORCE ROW LEVEL SECURITY"

    execute """
    CREATE POLICY cartulary_account_wall ON pipeline_runs
    USING (
      account_id = NULLIF(current_setting('memhouse.account_id', true), '')::uuid
    )
    WITH CHECK (
      account_id = NULLIF(current_setting('memhouse.account_id', true), '')::uuid
    )
    """
  end

  def down do
    execute "DROP POLICY IF EXISTS cartulary_account_wall ON pipeline_runs"

    drop_if_exists index(:audit_events, [:account_id, :inserted_at, :id],
                     name: "audit_events_hash_chain_index"
                   )

    alter table(:audit_events) do
      remove :content_hash
      remove :category
    end

    alter table(:knowledge_items) do
      remove :statement_hash
    end

    drop_if_exists index(:messages, [:account_id, :extraction_completed_at],
                     name: "messages_extraction_reconciliation_index"
                   )

    alter table(:messages) do
      remove :extraction_completed_at
      remove :content_hash
    end

    drop_if_exists unique_index(:pipeline_runs, [:account_id, :idempotency_key],
                     name: "pipeline_runs_idempotency_key_index"
                   )

    drop_if_exists index(:pipeline_runs, [:account_id, :kind, :status],
                     name: "pipeline_runs_reconciliation_index"
                   )

    drop table(:pipeline_runs)
  end
end
