# SPDX-License-Identifier: MemHouse-Sustainable-Use-1.0

defmodule MemHouse.Repo.Migrations.F6DocumentsConnectorsSync do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:document_chunks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :document_id, :uuid, null: false
      add :document_version_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :position, :bigint, null: false
      add :start_byte, :bigint, null: false
      add :end_byte, :bigint, null: false
      add :text, :text, null: false
      add :content_hash, :text, null: false
      add :embedding, {:array, :float}, null: false
      add :embedding_provider, :text, null: false
      add :embedding_model, :text, null: false
      add :embedding_version, :text, null: false
      add :embedding_dimensions, :bigint, null: false
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:document_chunks, [:account_id, :document_version_id, :position],
             name: "document_chunks_version_position_index"
           )

    alter table(:documents) do
      add :connector_config_id, :uuid
      add :current_content_hash, :text
      add :source_uri, :text
      add :source_metadata, :map, null: false, default: %{}
      add :tombstoned_at, :utc_datetime_usec
    end

    drop_if_exists unique_index(:documents, [:account_id, :external_id],
                     name: "documents_external_id_index"
                   )

    create unique_index(:documents, [:account_id, :connector_config_id, :external_id],
             name: "documents_source_external_id_index"
           )

    execute "DROP INDEX IF EXISTS document_versions_search_vector_idx"
    execute "ALTER TABLE document_versions DROP COLUMN IF EXISTS search_vector"

    alter table(:document_versions) do
      modify :content, :text, null: true
      add :byte_size, :bigint, null: false, default: 0
      add :blob_ref, :text
      add :source_metadata, :map, null: false, default: %{}
      add :extracted_text, :text
      add :extraction_metadata, :map, null: false, default: %{}
      add :chunk_count, :bigint, null: false, default: 0
      add :embedded_chunk_count, :bigint, null: false, default: 0
      add :processing_status, :text, null: false, default: "pending"
      add :last_error_class, :text
      add :extraction_completed_at, :utc_datetime_usec
    end

    create table(:connector_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :owner_peer_id, :uuid, null: false
      add :name, :text, null: false
      add :kind, :text, null: false
      add :schedule_seconds, :bigint, null: false, default: 3600
      add :config, :map, null: false, default: %{}
      add :secret_ref, :text
      add :cursor, :map, null: false, default: %{}
      add :status, :text, null: false, default: "active"
      add :next_sync_at, :utc_datetime_usec
      add :last_synced_at, :utc_datetime_usec
      add :last_error_class, :text
      add :consecutive_failures, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:connector_configs, [:account_id, :scope_id, :name],
             name: "connector_configs_scope_name_index"
           )

    execute """
    UPDATE document_versions
    SET blob_ref = 'legacy-db://' || id::text,
        byte_size = octet_length(content)
    WHERE blob_ref IS NULL
    """

    alter table(:document_versions) do
      modify :blob_ref, :text, null: false
    end

    execute """
    ALTER TABLE document_versions
    ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
      to_tsvector('english', coalesce(extracted_text, content, ''))
    ) STORED
    """

    execute """
    CREATE INDEX document_versions_search_vector_idx
    ON document_versions USING GIN (search_vector)
    """

    install_foreign_keys()
    install_indexes_and_constraints()
    install_rls()
  end

  def down do
    remove_rls()
    remove_indexes_and_constraints()
    remove_foreign_keys()

    drop_if_exists unique_index(:connector_configs, [:account_id, :scope_id, :name],
                     name: "connector_configs_scope_name_index"
                   )

    drop table(:connector_configs)

    execute """
    UPDATE document_versions
    SET content = coalesce(content, extracted_text, '')
    WHERE content IS NULL
    """

    execute "DROP INDEX IF EXISTS document_versions_search_vector_idx"
    execute "ALTER TABLE document_versions DROP COLUMN IF EXISTS search_vector"

    alter table(:document_versions) do
      remove :extraction_completed_at
      remove :last_error_class
      remove :processing_status
      remove :embedded_chunk_count
      remove :chunk_count
      remove :extraction_metadata
      remove :extracted_text
      remove :source_metadata
      remove :blob_ref
      remove :byte_size
      modify :content, :text, null: false
    end

    execute """
    ALTER TABLE document_versions
    ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (to_tsvector('english', coalesce(content, ''))) STORED
    """

    execute """
    CREATE INDEX document_versions_search_vector_idx
    ON document_versions USING GIN (search_vector)
    """

    drop_if_exists unique_index(:documents, [:account_id, :connector_config_id, :external_id],
                     name: "documents_source_external_id_index"
                   )

    create unique_index(:documents, [:account_id, :external_id],
             name: "documents_external_id_index"
           )

    alter table(:documents) do
      remove :tombstoned_at
      remove :source_metadata
      remove :source_uri
      remove :current_content_hash
      remove :connector_config_id
    end

    drop_if_exists unique_index(:document_chunks, [:account_id, :document_version_id, :position],
                     name: "document_chunks_version_position_index"
                   )

    drop table(:document_chunks)
  end

  defp install_foreign_keys do
    execute """
    ALTER TABLE connector_configs
    ADD CONSTRAINT connector_configs_account_id_fkey
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
    """

    execute """
    ALTER TABLE connector_configs
    ADD CONSTRAINT connector_configs_scope_id_fkey
    FOREIGN KEY (scope_id) REFERENCES scopes(id) ON DELETE CASCADE
    """

    execute """
    ALTER TABLE connector_configs
    ADD CONSTRAINT connector_configs_owner_peer_id_fkey
    FOREIGN KEY (owner_peer_id) REFERENCES peers(id) ON DELETE CASCADE
    """

    execute """
    ALTER TABLE documents
    ADD CONSTRAINT documents_connector_config_id_fkey
    FOREIGN KEY (connector_config_id) REFERENCES connector_configs(id) ON DELETE SET NULL
    """

    execute """
    ALTER TABLE document_chunks
    ADD CONSTRAINT document_chunks_account_id_fkey
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
    """

    execute """
    ALTER TABLE document_chunks
    ADD CONSTRAINT document_chunks_document_id_fkey
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
    """

    execute """
    ALTER TABLE document_chunks
    ADD CONSTRAINT document_chunks_document_version_id_fkey
    FOREIGN KEY (document_version_id) REFERENCES document_versions(id) ON DELETE CASCADE
    """

    execute """
    ALTER TABLE document_chunks
    ADD CONSTRAINT document_chunks_scope_id_fkey
    FOREIGN KEY (scope_id) REFERENCES scopes(id) ON DELETE CASCADE
    """
  end

  defp remove_foreign_keys do
    execute "ALTER TABLE document_chunks DROP CONSTRAINT IF EXISTS document_chunks_scope_id_fkey"

    execute "ALTER TABLE document_chunks DROP CONSTRAINT IF EXISTS document_chunks_document_version_id_fkey"

    execute "ALTER TABLE document_chunks DROP CONSTRAINT IF EXISTS document_chunks_document_id_fkey"

    execute "ALTER TABLE document_chunks DROP CONSTRAINT IF EXISTS document_chunks_account_id_fkey"

    execute "ALTER TABLE documents DROP CONSTRAINT IF EXISTS documents_connector_config_id_fkey"

    execute "ALTER TABLE connector_configs DROP CONSTRAINT IF EXISTS connector_configs_owner_peer_id_fkey"

    execute "ALTER TABLE connector_configs DROP CONSTRAINT IF EXISTS connector_configs_scope_id_fkey"

    execute "ALTER TABLE connector_configs DROP CONSTRAINT IF EXISTS connector_configs_account_id_fkey"
  end

  defp install_indexes_and_constraints do
    execute "CREATE INDEX connector_configs_account_id_index ON connector_configs (account_id)"

    execute "CREATE INDEX connector_configs_next_sync_at_index ON connector_configs (account_id, status, next_sync_at)"

    execute "CREATE INDEX document_chunks_account_id_index ON document_chunks (account_id)"
    execute "CREATE INDEX document_chunks_document_id_index ON document_chunks (document_id)"
    execute "CREATE INDEX document_chunks_scope_id_index ON document_chunks (scope_id)"
    execute "CREATE INDEX documents_connector_config_id_index ON documents (connector_config_id)"

    execute "CREATE INDEX provenances_document_version_id_index ON provenances (document_version_id)"

    execute """
    CREATE UNIQUE INDEX documents_upload_external_id_index
    ON documents (account_id, external_id)
    WHERE connector_config_id IS NULL
    """

    create constraint(:connector_configs, :connector_configs_schedule_seconds_positive,
             check: "schedule_seconds > 0"
           )

    create constraint(:document_chunks, :document_chunks_position_non_negative,
             check:
               "position >= 0 AND start_byte >= 0 AND end_byte >= start_byte AND embedding_dimensions > 0"
           )

    create constraint(:document_versions, :document_versions_counts_non_negative,
             check: "byte_size >= 0 AND chunk_count >= 0 AND embedded_chunk_count >= 0"
           )
  end

  defp remove_indexes_and_constraints do
    drop_if_exists constraint(:document_versions, :document_versions_counts_non_negative)
    drop_if_exists constraint(:document_chunks, :document_chunks_position_non_negative)

    drop_if_exists constraint(
                     :connector_configs,
                     :connector_configs_schedule_seconds_positive
                   )

    execute "DROP INDEX IF EXISTS documents_upload_external_id_index"
    execute "DROP INDEX IF EXISTS provenances_document_version_id_index"
    execute "DROP INDEX IF EXISTS documents_connector_config_id_index"
    execute "DROP INDEX IF EXISTS document_chunks_scope_id_index"
    execute "DROP INDEX IF EXISTS document_chunks_document_id_index"
    execute "DROP INDEX IF EXISTS document_chunks_account_id_index"
    execute "DROP INDEX IF EXISTS connector_configs_next_sync_at_index"
    execute "DROP INDEX IF EXISTS connector_configs_account_id_index"
  end

  defp install_rls do
    Enum.each(~w(connector_configs document_chunks), fn table_name ->
      execute "ALTER TABLE #{table_name} ENABLE ROW LEVEL SECURITY"
      execute "ALTER TABLE #{table_name} FORCE ROW LEVEL SECURITY"

      execute """
      CREATE POLICY cartulary_account_wall ON #{table_name}
      USING (
        account_id = NULLIF(current_setting('memhouse.account_id', true), '')::uuid
      )
      WITH CHECK (
        account_id = NULLIF(current_setting('memhouse.account_id', true), '')::uuid
      )
      """
    end)
  end

  defp remove_rls do
    Enum.each(~w(document_chunks connector_configs), fn table_name ->
      execute "DROP POLICY IF EXISTS cartulary_account_wall ON #{table_name}"
      execute "ALTER TABLE #{table_name} NO FORCE ROW LEVEL SECURITY"
      execute "ALTER TABLE #{table_name} DISABLE ROW LEVEL SECURITY"
    end)
  end
end
