# SPDX-License-Identifier: MemHouse-Sustainable-Use-1.0

defmodule MemHouse.Repo.Migrations.F4RealGateABGovernance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @account_tables ~w(
    knowledge_consents
    gate_decisions
    peer_query_deliveries
    validation_items
    peer_ask_preferences
    governance_gate_rules
    erasure_requests
    peer_queries
  )

  def up do
    create table(:knowledge_consents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :knowledge_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :subject_peer_id, :uuid, null: false
      add :target_scope_id, :uuid, null: false
      add :status, :text, null: false, default: "pending"
      add :channel, :text
      add :verified, :boolean, null: false, default: false
      add :decided_by_peer_id, :uuid
      add :decided_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(
             :knowledge_consents,
             [:account_id, :knowledge_id, :subject_peer_id, :target_scope_id],
             name: "knowledge_consents_knowledge_target_index"
           )

    create table(:gate_decisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :validation_item_id, :uuid
      add :knowledge_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :gate, :text, null: false
      add :decision, :text, null: false
      add :actor_peer_id, :uuid
      add :channel, :text, null: false
      add :verified, :boolean, null: false, default: false
      add :from_state, :text
      add :to_state, :text
      add :from_level, :text
      add :to_level, :text
      add :statement_hash, :text, null: false
      add :metadata, :map, null: false, default: %{}
      add :decided_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:peer_query_deliveries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :peer_query_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :peer_id, :uuid, null: false
      add :session_id, :uuid, null: false
      add :tool_name, :text, null: false
      add :delivered_at, :utc_datetime_usec, null: false
      add :shown_text_hash, :text
      add :verification, :text, null: false, default: "pending"
      add :answered_at, :utc_datetime_usec
      add :verdict, :text
      add :conflict, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:peer_query_deliveries, [:account_id, :peer_query_id, :session_id],
             name: "peer_query_deliveries_query_session_index"
           )

    create table(:validation_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :knowledge_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :subject_peer_id, :uuid
      add :target_scope_id, :uuid
      add :target_level, :text, null: false
      add :kind, :text, null: false
      add :state, :text, null: false, default: "pending"
      add :decision, :text
      add :statement_hash, :text, null: false
      add :confidence, :float, null: false
      add :sensitivity, :text, null: false
      add :provenance_ids, {:array, :uuid}, null: false, default: []
      add :conflict_knowledge_ids, {:array, :uuid}, null: false, default: []
      add :assigned_peer_id, :uuid
      add :due_at, :utc_datetime_usec, null: false
      add :escalated_at, :utc_datetime_usec
      add :attempt_count, :bigint, null: false, default: 0
      add :decided_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:validation_items, [:account_id, :knowledge_id, :kind],
             name: "validation_items_open_knowledge_gate_index"
           )

    create table(:peer_ask_preferences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :peer_id, :uuid, null: false
      add :max_per_session, :bigint, null: false, default: 3
      add :max_per_day, :bigint, null: false, default: 10
      add :paused_until, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:peer_ask_preferences, [:account_id, :peer_id],
             name: "peer_ask_preferences_peer_index"
           )

    alter table(:knowledge_items) do
      add :target_level, :text, null: false, default: "peer"
      add :verification, :text, null: false, default: "pending"
      add :held_scope_id, :uuid
      add :corroboration_count, :bigint, null: false, default: 1
      add :supersedes_id, :uuid
      add :deleted_at, :utc_datetime_usec
    end

    create table(:governance_gate_rules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :scope_id, :uuid
      add :target_level, :text, null: false
      add :sensitivity, :text, null: false
      add :minimum_confidence, :float, null: false, default: 1.0
      add :gate_a_mode, :text, null: false, default: "human"
      add :gate_b_mode, :text, null: false, default: "human"
      add :minimum_corroboration, :bigint, null: false, default: 1
      add :requires_consent, :boolean, null: false, default: false
      add :pending_max_age_hours, :bigint, null: false, default: 168
      add :revalidate_after_days, :bigint
      add :priority, :bigint, null: false, default: 0
      add :version, :bigint, null: false, default: 1
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(
             :governance_gate_rules,
             [:account_id, :scope_id, :target_level, :sensitivity, :version],
             name: "governance_gate_rules_matrix_cell_index"
           )

    create table(:erasure_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :peer_id, :uuid, null: false
      add :scope_id, :uuid
      add :mode, :text, null: false, default: "proportionate"
      add :requested_by_peer_id, :uuid
      add :state, :text, null: false, default: "pending"
      add :affected_counts, :map, null: false, default: %{}
      add :requested_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:peer_queries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :validation_item_id, :uuid, null: false
      add :knowledge_id, :uuid, null: false
      add :scope_id, :uuid, null: false
      add :peer_id, :uuid, null: false
      add :kind, :text, null: false
      add :statement_text, :text, null: false
      add :statement_hash, :text, null: false
      add :state, :text, null: false, default: "pending"
      add :deadline_at, :utc_datetime_usec, null: false
      add :attempts, :bigint, null: false, default: 0
      add :last_delivered_at, :utc_datetime_usec
      add :answered_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:peer_queries, [:account_id, :knowledge_id, :kind],
             name: "peer_queries_knowledge_kind_index"
           )

    execute """
    UPDATE knowledge_items
    SET verification = CASE
      WHEN state = 'active' THEN 'legacy_poc'
      ELSE 'pending'
    END
    """

    create index(:gate_decisions, [:account_id, :knowledge_id, :decided_at])
    create index(:validation_items, [:account_id, :state, :due_at])
    create index(:peer_queries, [:account_id, :peer_id, :state, :deadline_at])
    create index(:peer_query_deliveries, [:account_id, :peer_id, :delivered_at])
    create index(:erasure_requests, [:account_id, :peer_id, :requested_at])

    create constraint(:governance_gate_rules, :gate_rules_target_level,
             check: "target_level IN ('peer', 'scope', 'account')"
           )

    create constraint(:governance_gate_rules, :gate_rules_sensitivity,
             check: "sensitivity IN ('public', 'internal', 'personal', 'restricted')"
           )

    create constraint(:governance_gate_rules, :gate_rules_gate_a_mode,
             check: "gate_a_mode IN ('human', 'auto_keep', 'auto_reject')"
           )

    create constraint(:governance_gate_rules, :gate_rules_gate_b_mode,
             check: "gate_b_mode IN ('human', 'auto_place', 'hold')"
           )

    create constraint(:governance_gate_rules, :gate_rules_confidence,
             check: "minimum_confidence >= 0.0 AND minimum_confidence <= 1.0"
           )

    create constraint(:validation_items, :validation_items_state,
             check:
               "state IN ('pending', 'deferred', 'awaiting_consent', 'escalated', 'approved', 'rejected', 'merged')"
           )

    create constraint(:peer_queries, :peer_queries_state,
             check: "state IN ('pending', 'delivered', 'answered', 'expired', 'superseded')"
           )

    create constraint(:peer_query_deliveries, :peer_query_delivery_verification,
             check: "verification IN ('pending', 'verified', 'unverified_channel')"
           )

    create constraint(:knowledge_consents, :knowledge_consents_status,
             check: "status IN ('pending', 'granted', 'denied', 'revoked')"
           )

    create constraint(:erasure_requests, :erasure_requests_mode,
             check: "mode IN ('proportionate', 'strict')"
           )

    create constraint(:erasure_requests, :erasure_requests_state,
             check: "state IN ('pending', 'completed', 'failed')"
           )

    install_rls()
  end

  def down do
    remove_rls()

    drop_if_exists unique_index(:peer_queries, [:account_id, :knowledge_id, :kind],
                     name: "peer_queries_knowledge_kind_index"
                   )

    drop table(:peer_queries)

    drop table(:erasure_requests)

    drop_if_exists unique_index(
                     :governance_gate_rules,
                     [:account_id, :scope_id, :target_level, :sensitivity, :version],
                     name: "governance_gate_rules_matrix_cell_index"
                   )

    drop table(:governance_gate_rules)

    alter table(:knowledge_items) do
      remove :deleted_at
      remove :supersedes_id
      remove :corroboration_count
      remove :held_scope_id
      remove :verification
      remove :target_level
    end

    drop_if_exists unique_index(:peer_ask_preferences, [:account_id, :peer_id],
                     name: "peer_ask_preferences_peer_index"
                   )

    drop table(:peer_ask_preferences)

    drop_if_exists unique_index(:validation_items, [:account_id, :knowledge_id, :kind],
                     name: "validation_items_open_knowledge_gate_index"
                   )

    drop table(:validation_items)

    drop_if_exists unique_index(
                     :peer_query_deliveries,
                     [:account_id, :peer_query_id, :session_id],
                     name: "peer_query_deliveries_query_session_index"
                   )

    drop table(:peer_query_deliveries)

    drop table(:gate_decisions)

    drop_if_exists unique_index(
                     :knowledge_consents,
                     [:account_id, :knowledge_id, :subject_peer_id, :target_scope_id],
                     name: "knowledge_consents_knowledge_target_index"
                   )

    drop table(:knowledge_consents)
  end

  defp install_rls do
    Enum.each(@account_tables, fn table_name ->
      execute "ALTER TABLE #{table_name} ENABLE ROW LEVEL SECURITY"
      execute "ALTER TABLE #{table_name} FORCE ROW LEVEL SECURITY"

      execute """
      CREATE POLICY cartulary_account_wall ON #{table_name}
      USING (
        account_id = NULLIF(current_setting('memhouse.account_id', true), '')::uuid
      )
      WITH CHECK (
        account_id = NULLIF(current_setting('memhouse.account_id', true), '')::uuid
      )
      """
    end)
  end

  defp remove_rls do
    Enum.each(Enum.reverse(@account_tables), fn table_name ->
      execute "DROP POLICY IF EXISTS cartulary_account_wall ON #{table_name}"
      execute "ALTER TABLE #{table_name} NO FORCE ROW LEVEL SECURITY"
      execute "ALTER TABLE #{table_name} DISABLE ROW LEVEL SECURITY"
    end)
  end
end
