# SPDX-License-Identifier: MemHouse-Sustainable-Use-1.0

defmodule MemHouse.Repo.Migrations.F7RetrievalEntityContext do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:entities) do
      add :alias_embedding, :vector
      add :embedding_provider, :text
      add :embedding_model, :text
      add :embedding_version, :text
      add :embedding_dimensions, :bigint
    end

    alter table(:projections) do
      add :cache_key, :text
      add :watermark, :utc_datetime_usec
      add :delta_count, :bigint, null: false, default: 0
    end

    execute """
    UPDATE projections
    SET cache_key = 'legacy:' || id::text
    WHERE cache_key IS NULL
    """

    alter table(:projections) do
      modify :cache_key, :text, null: false
    end

    create unique_index(:projections, [:account_id, :cache_key],
             name: "projections_cache_key_index"
           )

    execute """
    ALTER TABLE document_chunks
    ALTER COLUMN embedding TYPE vector
    USING embedding::vector
    """

    alter table(:knowledge_items) do
      add :embedding, :vector
      add :embedding_dimensions, :bigint
    end

    execute """
    ALTER TABLE document_chunks
    ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (to_tsvector('english', coalesce(text, ''))) STORED
    """

    execute """
    CREATE INDEX document_chunks_search_vector_idx
    ON document_chunks USING GIN (search_vector)
    """

    execute """
    CREATE INDEX knowledge_items_embedding_hnsw_384_idx
    ON knowledge_items
    USING hnsw ((embedding::vector(384)) vector_cosine_ops)
    WHERE embedding IS NOT NULL AND embedding_dimensions = 384
    """

    execute """
    CREATE INDEX document_chunks_embedding_hnsw_384_idx
    ON document_chunks
    USING hnsw ((embedding::vector(384)) vector_cosine_ops)
    WHERE embedding_dimensions = 384 AND status = 'active'
    """

    execute """
    CREATE INDEX entities_alias_embedding_hnsw_384_idx
    ON entities
    USING hnsw ((alias_embedding::vector(384)) vector_cosine_ops)
    WHERE alias_embedding IS NOT NULL AND embedding_dimensions = 384
    """

    execute """
    CREATE INDEX entity_mentions_scope_entity_idx
    ON entity_mentions (account_id, scope_id, entity_id)
    """

    execute """
    CREATE INDEX knowledge_relations_expand_idx
    ON knowledge_relations (account_id, source_knowledge_id, target_knowledge_id)
    """
  end

  def down do
    execute "DROP INDEX IF EXISTS knowledge_relations_expand_idx"
    execute "DROP INDEX IF EXISTS entity_mentions_scope_entity_idx"
    execute "DROP INDEX IF EXISTS entities_alias_embedding_hnsw_384_idx"
    execute "DROP INDEX IF EXISTS document_chunks_embedding_hnsw_384_idx"
    execute "DROP INDEX IF EXISTS knowledge_items_embedding_hnsw_384_idx"
    execute "DROP INDEX IF EXISTS document_chunks_search_vector_idx"
    execute "ALTER TABLE document_chunks DROP COLUMN IF EXISTS search_vector"

    alter table(:knowledge_items) do
      remove :embedding_dimensions
      remove :embedding
    end

    execute """
    ALTER TABLE document_chunks
    ALTER COLUMN embedding TYPE float8[]
    USING embedding::real[]::float8[]
    """

    drop_if_exists unique_index(:projections, [:account_id, :cache_key],
                     name: "projections_cache_key_index"
                   )

    alter table(:projections) do
      remove :delta_count
      remove :watermark
      remove :cache_key
    end

    alter table(:entities) do
      remove :embedding_dimensions
      remove :embedding_version
      remove :embedding_model
      remove :embedding_provider
      remove :alias_embedding
    end
  end
end
