defmodule MemHouse.Repo.Migrations.AddAccountConsentMode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts) do
      add :consent_mode, :text, null: false, default: "subject_required"
    end
  end

  def down do
    alter table(:accounts) do
      remove :consent_mode
    end
  end
end
