defmodule MemHouse.Repo.Migrations.Issue302ProjectionExpiryBound do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projections) do
      add :valid_until, :utc_datetime_usec
      add :validity_version, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:projections) do
      remove :validity_version
      remove :valid_until
    end
  end
end
