# SPDX-License-Identifier: MemHouse-Sustainable-Use-1.0

defmodule MemHouse.Repo.Migrations.F3IdentityTenancyBasicRbac do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "CREATE EXTENSION IF NOT EXISTS citext"

    alter table(:role_grants) do
      add :effect, :text, null: false, default: "allow"
      add :granted_by_peer_id, :uuid
      add :granted_at, :utc_datetime_usec
    end

    execute "UPDATE role_grants SET granted_at = inserted_at WHERE granted_at IS NULL"

    alter table(:role_grants) do
      modify :granted_at, :utc_datetime_usec, null: false
    end

    create constraint(:role_grants, :role_grants_role_check,
             check: "role IN ('account-admin', 'curator', 'member', 'reader')"
           )

    create constraint(:role_grants, :role_grants_effect_check,
             check: "effect IN ('allow', 'deny')"
           )

    drop_if_exists unique_index(:role_grants, [:account_id, :scope_id, :peer_id],
                     name: "role_grants_unique_grant_index"
                   )

    create unique_index(:role_grants, [:account_id, :scope_id, :peer_id, :role, :effect],
             name: "role_grants_unique_grant_index"
           )

    alter table(:peers) do
      add :email, :citext
      add :hashed_password, :text
    end

    create unique_index(:peers, [:account_id, :email], name: "peers_unique_email_index")

    alter table(:external_identities) do
      add :assurance, :text, null: false, default: "medium"
      add :linked_at, :utc_datetime_usec
      add :active, :boolean, null: false, default: true
    end

    execute """
    UPDATE external_identities
    SET linked_at = inserted_at
    WHERE linked_at IS NULL
    """

    alter table(:external_identities) do
      modify :linked_at, :utc_datetime_usec, null: false
    end

    create constraint(:external_identities, :external_identities_assurance_check,
             check: "assurance IN ('low', 'medium', 'high')"
           )

    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :account_id,
          references(:accounts,
            column: :id,
            name: "api_keys_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :peer_id,
          references(:peers,
            column: :id,
            name: "api_keys_peer_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :scope_id,
          references(:scopes,
            column: :id,
            name: "api_keys_scope_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :api_key_hash, :binary, null: false
      add :expires_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:api_keys, [:account_id, :api_key_hash],
             name: "api_keys_unique_api_key_index"
           )

    create index(:api_keys, [:account_id, :peer_id])

    alter table(:accounts) do
      add :edition_slot, :text
    end

    create unique_index(:accounts, [:edition_slot],
             name: "accounts_one_community_free_slot_index",
             where: "edition_slot = 'community-free'"
           )

    execute "ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY"
    execute "ALTER TABLE api_keys FORCE ROW LEVEL SECURITY"

    execute """
    CREATE POLICY cartulary_account_wall ON api_keys
      USING (
        account_id = NULLIF(current_setting('memhouse.account_id', true), '')::uuid
      )
      WITH CHECK (
        account_id = NULLIF(current_setting('memhouse.account_id', true), '')::uuid
      )
    """

    execute """
    CREATE OR REPLACE FUNCTION cartulary_resolve_api_key_account(requested_key_id uuid)
    RETURNS uuid
    LANGUAGE sql
    STABLE
    SECURITY DEFINER
    SET search_path = pg_catalog, public
    SET row_security = off
    AS $function$
      SELECT account_id
      FROM public.api_keys
      WHERE id = requested_key_id
      LIMIT 1
    $function$
    """

    execute "REVOKE ALL ON FUNCTION cartulary_resolve_api_key_account(uuid) FROM PUBLIC"
  end

  def down do
    execute "DROP FUNCTION IF EXISTS cartulary_resolve_api_key_account(uuid)"

    alter table(:accounts) do
      remove :edition_slot
    end

    drop constraint(:api_keys, "api_keys_account_id_fkey")

    drop constraint(:api_keys, "api_keys_peer_id_fkey")
    drop constraint(:api_keys, "api_keys_scope_id_fkey")

    drop_if_exists unique_index(:api_keys, [:account_id, :api_key_hash],
                     name: "api_keys_unique_api_key_index"
                   )

    drop table(:api_keys)

    alter table(:external_identities) do
      remove :active
      remove :linked_at
      remove :assurance
    end

    drop_if_exists unique_index(:peers, [:account_id, :email], name: "peers_unique_email_index")

    alter table(:peers) do
      remove :hashed_password
      remove :email
    end

    drop_if_exists unique_index(:role_grants, [:account_id, :scope_id, :peer_id, :role, :effect],
                     name: "role_grants_unique_grant_index"
                   )

    create unique_index(:role_grants, [:account_id, :scope_id, :peer_id],
             name: "role_grants_unique_grant_index"
           )

    alter table(:role_grants) do
      remove :granted_at
      remove :granted_by_peer_id
      remove :effect
    end
  end
end
